### ISSUE TITLE
model Stay

### ISSUE THREAD

**Issue by gdsc-nits** [gdsc-nits-org/askaplace-api#2]
The application will also contain details about the nearby stay options (hotels, restrooms, lodge, PG, homestay etc). For that, create a model named `Stay` containing `id`,`name`,`type`,`website`,`location`,`landmark`,`contact`,`manager`. The `id` is auto generated and acts as primary key. `name` contains the name of the stay (eg: hotel name, pg name, lodge name etc). `type` is the type of stay (eg: hotel, lodge, PG, homestay etc). `website`: this key is optional. Some stays might have their own websites or social media handles. It will simply contain that link as a string.  `location` stores the exact coordinates of the stay, in latitudes and longitudes. `landmark` stores the name of any significant landmark near the stay so that it is easier for the tourist to locate it. `manager` contains the name of person-in-charge of the stay.

Deadline for this task is 22 December,2024, EOD.

**Comment by Manashgoswamii** [comment]
#5

**Comment by gdsc-nits** [comment]
Done
